package CleanCodeSFP.airLines.staffOfAirLine;

public enum StaffDepartment { MANAGEMENT, ACCOUNTANT, COMMERCIAL, AIRCRAFT_GROUND_SERVICES,
    AIRLINE_GROUND_SERVICE, PASSENGER_SERVICE, LOAD_SERVICE, SECURITY,FLIGHT_CREW}
