package OlgaVersionAirportProject.airLines.service;

public enum ServiceOfAirLine { CARGO_SERVICE, PASSENGER_SERVICE,
    PASSENGERS_CARGO_SERVICE, SPECIAL_LITERAL_SERVICE, PASSENGERS_CARGO_LITERAL_SERVICE}
