package OlgaVersionAirportProject.airLines.flights;

public enum TypeOfFlights {
    REGULAR_PASSENGER_FLIGHT, CARGO_FLIGHT, CHARTER_PASSENGER_FLIGHT,
    CHARTER_CARGO_FLIGHT, LETTER_FLIGHT, ALL_TYPE_OF_FLIGHTS
}
